language: go
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.8
  - go: 1.9
  - go: tip
  allow_failures:
  - go: tip
cache:
  directories:
  - "$GOPATH/src"
  - "$GOPATH/pkg"
install:
- make deps
- make restore
- export CI=TRAVIS
script:
- make ci
- if [ "${LATEST}" = "true" ]; then make build/release; fi
deploy:
  provider: releases
  skip_cleanup: true
  file:
  - bin/gibson
  - bin/gibson_darwin_386
  - bin/gibson_darwin_amd64
  - bin/gibson_linux_386
  - bin/gibson_linux_amd64
  on:
    repo: axelspringer/gibson
    tags: true
    condition: "$LATEST = true"
  api_key:
    secure: dInBGFmD/TkhRd8nOTfqVwVxuDcVEjtjPInVjerAfmFAaVZfNSVM+wRPmgENk7jnbAoDJO4ORJ0gBFBoGYF2aWm2s5kUUxgVAJ4SUDoaFfEPLJAGH8Fi2koxt2DZpgha8dqXIo7zsxn7Lfglff6bgq0806KxCel9wHT49d6QOFX8iwJXxAm+poEEsgLQ88oBe8FN7skD6mTvzY5iELoXguoNYowu5qffP+jsffpKij3zsTNH/igote0OkF6tBhKOVs1eqA/EiueClnYtlwOxM7V5CVT+XbWZGBtjvBc+ADgLH54MuMysKcW7qIThEeelzf4O3jzRZUBFlL8N675uLPVfbyhFfsyaTTvd6ew3FfPainH5MkGNj8yCP24aQtwgvt08a6HSpdzxd7fTnSUQ7VujL3J9jCls7wpzWpLohqer0mIP7psFqb444ORH8PCuwrwrpW5JchkYjKJrEKxp0Nt88d02gDLyvVGjByBND9fuJaxXV8tDKA8mDO3PzAQugRzP5fmvHgwsGQEe7J/erWb9H6iEZt+5NFHmDzrhmFaZ72I3eHvQ8LxTnUBj6Vv0xwlQBtV0faRo65/OYdajgFl6fhfE9FecH+DeKRXKsKQ/vtaVr14vV5HfxcjpMxQvaRapKDcCKK50LizB3EB1qkuF7H4bRPC9ZDCsl5kmGUQ=
notifications:
  slack:
    secure: Jn1kygEuJ3z/BGmA/Obp4o4eD2OaPXzqV+eOwfujmOsxVs0ePBsYmWxtrG3rIC3dCeoNtj9n6j5pcx+UPeZ/SINi/2d39k9BJNUSDatiO3HaQ5EtizXAL4i3mNcutU06iUS8GZlZGYHGxwAXzKJNsyOQmKgKTijN8937KV7v8ROhsNdzAvEOdNacR031XDPBwjyr/8LErpfKOjKC1btYdxKGoD6cjLLBj3W5XhLvaPo6RUP4X+qMh3CmTobnNLyvSF8RxmNdOO+j5FtYBlF4Kq3Dkfl2uiF/cOlpidtd1n/BMfuUW0oIcF/B7Q9C2kjvsIBtmvVk7Dc+wnwU85EzcvGwk9bYl5b7MP+YpDmRmbFJClRwx2UphHNPFhiaILgiLplfp16yDC7wQ4tOIpC5QRI4gfc65y+DfD5+YFmxlb4g4Colfe76Npo34mltwNYSodh9cLVq0Wx1qvf4UWUAJkPziL8RfDd86viWMNzEH8ZYox5BjZMhM2a0cws880CrBEXgFdCvcRQzWU2Iq6MSKHJiEdjYo7ppM0Cmi4DzJVSKWRpuZfgzqutdFY6bIpa8kyQyu33cVLe8AkVNKwa4pYO9OnLxDpDHb/5CV86jwFbSEMy+PRZQQNeRTYYBADX6quooT+ETBBYQcOx1p8f88VlWHV1TMMnSxItBjLG616g=
